version: '3.4'

services:
  categorydb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0

  category.api:
    image: ${DOCKER_REGISTRY-}categoryapi
    build:
      context: .
      dockerfile: Services/Category/Category.API/Dockerfile

volumes:
  elasticsearch-data:


